CREATE TABLE [dbo].[FT_GL_Account](
	[coa_id] [int] NOT NULL,
	[period_id] [int] NOT NULL,
	[bu_id] [int] NOT NULL,
	[source_id] [int] NOT NULL,
	[segment1_id] [int] NULL,
	[segment2_id] [int] NULL,
	[user_listing_id] [int] NULL,
	[approved_by_id] [int] NULL,
	[ey_period] [nvarchar](50) NULL,
	[year_flag] [nvarchar](4) NULL,
	[period_flag] [nvarchar](4) NULL,
	[dr_cr_ind] [char](1) NULL,
	[reversal_ind] [char](1) NULL,
	[Sys_man_ind] [char](1) NULL,
	[journal_type] [nvarchar](25) NULL,
	[entry_date_id] [int] NULL,
	[effective_date_id] [int] NULL,
	[amount_curr_cd] [nvarchar](50) NULL,
	[reporting_amount_curr_cd] [nvarchar](50) NULL,
	[functional_curr_cd] [nvarchar](50) NULL,
	[net_amount] [float] NULL,
	[net_amount_credit] [float] NULL,
	[net_amount_debit] [float] NULL,
	[net_reporting_amount] [float] NULL,
	[net_reporting_amount_debit] [float] NULL,
	[net_reporting_amount_credit] [float] NULL,
	[net_functional_amount] [float] NULL,
	[net_functional_amount_debit] [float] NULL,
	[net_functional_amount_credit] [float] NULL,
	[count_je_id] INT NULL

) ON [PRIMARY]