#!/bin/sh

# vagrant-checkstatus.sh generated by https://github.com/timveil/hdp-vagrant-generator on 5/17/15 10:23 AM



echo " "
echo "---------------------------------------------------------------------------------------------------------------"
echo "----- Waiting for Cluster Install to Finish"
echo "---------------------------------------------------------------------------------------------------------------"
echo " "

PROGRESS=0
until [ $PROGRESS -eq 100 ]; do
    PROGRESS=`curl --silent --show-error -H "X-Requested-By: ambari" -X GET -u admin:admin http://hivetest.hdp.local:8080/api/v1/clusters/hive-test/requests/1 2>&1 | grep -oP '\"progress_percent\"\s+\:\s+\K[0-9]+'`
    echo -ne "$PROGRESS percent complete!"\\r
    sleep 5
done

echo " "
echo "---------------------------------------------------------------------------------------------------------------"
echo "----- Adding Admin User"
echo "---------------------------------------------------------------------------------------------------------------"
echo " "

useradd -G hdfs admin
usermod -a -G users admin
usermod -a -G hadoop admin

echo " "
echo "---------------------------------------------------------------------------------------------------------------"
echo "----- Updating Vagrant User"
echo "---------------------------------------------------------------------------------------------------------------"
echo " "

usermod -a -G users vagrant
usermod -a -G hdfs vagrant
usermod -a -G hadoop vagrant

echo " "
echo "---------------------------------------------------------------------------------------------------------------"
echo "----- Cluster Install Complete!  http://hivetest.hdp.local:8080"
echo "---------------------------------------------------------------------------------------------------------------"
echo " "

