CREATE TABLE DIM_Chart_of_Accounts (
  Coa_id INT NOT NULL,
  bu_id INT NULL,
  coa_effective_date_id INT NULL,
  gl_account_cd VARCHAR(200) NULL,
  gl_subacct_cd VARCHAR(200) NULL,
  gl_account_name VARCHAR(200) NULL,
  gl_subacct_name VARCHAR(200) NULL,
  consolidation_account VARCHAR(200) NULL,
  ey_gl_account_name VARCHAR(400) NULL,
  ey_account_type VARCHAR(200) NULL,
  ey_account_sub_type VARCHAR(200) NULL,
  ey_account_class VARCHAR(200) NULL,
  ey_account_sub_class VARCHAR(200) NULL,
  ey_account_group_I VARCHAR(200) NULL,
  ey_account_group_II VARCHAR(200) NULL,
  ey_cash_activity VARCHAR(200) NULL,
  ey_index VARCHAR(200) NULL,
  ey_sub_index VARCHAR(200) NULL,
  created_by_id INT NULL,
  created_date_id INT NULL,
  created_time_id INT NULL,
  last_modified_by_id INT NULL,
  last_modified_date_id INT NULL,
  ver_desc VARCHAR(200) NULL,
  ver_start_date_id INT NULL,
  ver_end_date_id INT NULL
) stored AS orc;
