CREATE TABLE if not exists FLAT_JE (
  ID BIGINT IDENTITY(1, 1),
  je_id varchar (100) NOT NULL,
  je_line_id varchar (100) NOT NULL,
  je_line_desc varchar (250) NULL,
  je_header_desc varchar (250) NULL,
  dr_cr_ind CHAR(1) NULL,
  coa_id INT NOT NULL,
  period_id INT NOT NULL,
  bu_id INT NOT NULL,
  source_id INT NOT NULL,
  segment1_id INT NULL,
  segment2_id INT NULL,
  segment3_id INT NULL,
  segment4_id INT NULL,
  segment5_id INT NULL,
  ey_je_id varchar (100) NULL,
  activity varchar (100) NULL,
  approved_by_id INT NULL,
  transaction_type_id INT NOT NULL,
  reversal_ind CHAR(1) NULL,
  sys_manual_ind CHAR(1) NULL,
  year_flag varchar (25) NULL,
  period_flag varchar (25) NULL,
  year_flag_desc varchar (10) NULL,
  period_flag_desc varchar (100) NULL,
  year_end_date DATE NULL,
  period_end_date DATE NULL,
  gl_account_cd varchar (200) NULL,
  gl_subacct_cd varchar (200) NULL,
  gl_account_name varchar (200) NULL,
  gl_subacct_name varchar (200) NULL,
  ey_gl_account_name varchar (200) NULL,
  consolidation_account varchar (200) NULL,
  ey_account_type varchar (200) NULL,
  ey_account_sub_type varchar (200) NULL,
  ey_account_class varchar (200) NULL,
  ey_cash_activity varchar (200) NULL,
  ey_account_sub_class varchar (200) NULL,
  ey_index varchar (200) NULL,
  ey_sub_index varchar (200) NULL,
  ey_account_group_I varchar (200) NULL,
  ey_account_group_II varchar (200) NULL,
  sys_manual_ind_src CHAR(1) NULL,
  sys_manual_ind_usr CHAR(1) NULL,
  user_listing_id INT NULL,
  client_user_id varchar (25) NULL,
  preparer_ref varchar (200) NULL,
  first_name varchar (100) NULL,
  last_name varchar (100) NULL,
  full_name varchar (100) NULL,
  department varchar (100) NULL,
  role_resp varchar (100) NULL,
  title varchar (100) NULL,
  active_ind CHAR(1) NULL,
  transaction_type_group_desc varchar (100) NULL,
  transaction_type varchar (25) NULL,
  fiscal_period_cd varchar (50) NOT NULL,
  fiscal_period_desc varchar (100) NULL,
  fiscal_period_start varchar (50) NOT NULL,
  fiscal_period_end varchar (50) NOT NULL,
  fiscal_quarter_start varchar (50) NULL,
  fiscal_quarter_end varchar (50) NULL,
  fiscal_year_start varchar (50) NULL,
  fiscal_year_end varchar (50) NULL,
  EY_fiscal_year varchar (100) NULL,
  EY_quarter varchar (100) NULL,
  EY_period varchar (100) NULL,
  Entry_Date DATETIME NULL,
  Day_of_week varchar (25) NULL,
  Effective_Date DATETIME NULL,
  Lag_Date INT NULL,
  exchange_rate FLOAT NOT NULL,
  local_exchange_rate FLOAT NOT NULL,
  reporting_exchange_rate FLOAT NOT NULL,
  effective_date_id INT NOT NULL,
  entry_date_id INT NOT NULL,
  functional_curr_cd varchar (25) NOT NULL,
  functional_amount FLOAT NOT NULL,
  functional_debit_amount FLOAT NOT NULL,
  functional_credit_amount FLOAT NOT NULL,
  amount FLOAT NOT NULL,
  amount_debit FLOAT NOT NULL,
  amount_credit FLOAT NOT NULL,
  amount_curr_cd varchar (25) NOT NULL,
  reporting_amount FLOAT NOT NULL,
  reporting_amount_curr_cd varchar (25) NOT NULL,
  reporting_amount_debit FLOAT NOT NULL,
  reporting_amount_credit FLOAT NOT NULL,
  engagement_id uniqueidentifier NOT NULL,
  entry_time_id INT NOT NULL,
  last_modified_by_id INT NOT NULL,
  last_modified_date_id INT NOT NULL,
  approved_by_date_id INT NOT NULL,
  reversal_je_id varchar (100) NULL,
  GL_clearing_document varchar (100) NULL,
  GL_clearing_date_id INT NOT NULL,
  ver_start_date_id INT NOT NULL,
  ver_end_date_id INT NULL,
  ver_desc varchar (100) NULL,
  day_number_of_week INT NULL,
  day_number_of_month INT NULL,
  journal_type varchar (25) NULL,
  system_load_date DATETIME NOT NULL,
  approver_department varchar (250) NULL,
  approver_ref varchar (250) NULL,
  reporting_impact_to_assets FLOAT NULL,
  reporting_impact_to_equity FLOAT NULL,
  reporting_impact_to_expenses FLOAT NULL,
  reporting_impact_to_liabilities FLOAT NULL,
  reporting_impact_to_revenue FLOAT NULL,
  functional_impact_to_assets FLOAT NULL,
  functional_impact_to_equity FLOAT NULL,
  functional_impact_to_expenses FLOAT NULL,
  functional_impact_to_liabilities FLOAT NULL,
  functional_impact_to_revenue FLOAT NULL,
  ey_subledger_type varchar (30) NULL,
  ey_AR_type varchar (30) NULL,
  ey_AP_type varchar (30) NULL,
  ey_reconciliation_GL_group varchar (30) NULL,
  Adjusted_fiscal_period VARCHAR (50) NULL
)
