CREATE TABLE
    FT_GL_Account
    (
        coa_id INT NOT NULL,
        period_id INT NOT NULL,
        bu_id INT NOT NULL,
        source_id INT NOT NULL,
        segment1_id INT NULL,
        segment2_id INT NULL,
        user_listing_id INT NULL,
        approved_by_id INT NULL,
        ey_period nvarchar(50) NULL,
        year_flag nvarchar(4) NULL,
        period_flag nvarchar(4) NULL,
        dr_cr_ind CHAR(1) NULL,
        reversal_ind CHAR(1) NULL,
        Sys_man_ind CHAR(1) NULL,
        journal_type nvarchar(25) NULL,
        entry_date_id INT NULL,
        effective_date_id INT NULL,
        amount_curr_cd nvarchar(50) NULL,
        reporting_amount_curr_cd nvarchar(50) NULL,
        functional_curr_cd nvarchar(50) NULL,
        net_amount FLOAT NULL,
        net_amount_credit FLOAT NULL,
        net_amount_debit FLOAT NULL,
        net_reporting_amount FLOAT NULL,
        net_reporting_amount_debit FLOAT NULL,
        net_reporting_amount_credit FLOAT NULL,
        net_functional_amount FLOAT NULL,
        net_functional_amount_debit FLOAT NULL,
        net_functional_amount_credit FLOAT NULL,
        count_je_id INT NULL
    )
