CREATE TABLE Ft_JE_Amounts (
  je_id VARCHAR(200) NOT NULL,
  coa_id INT NOT NULL,
  period_id INT NOT NULL,
  bu_id INT NOT NULL,
  source_id INT NOT NULL,
  user_listing_id INT NULL,
  approved_by_id INT NULL,
  segment1_id INT NULL,
  segment2_id INT NULL,
  dr_cr_ind CHAR(1) NULL,
  reversal_ind CHAR(1) NULL,
  sys_manual_ind CHAR(1) NULL,
  Journal_type VARCHAR(25) NULL,
  year_flag CHAR(50) NULL,
  period_flag CHAR(50) NULL,
  ey_period VARCHAR(200) NULL,
  entry_date_id INT NULL,
  effective_date_id INT NULL,
  Net_amount FLOAT NULL,
  Net_amount_debit FLOAT NULL,
  Net_amount_credit FLOAT NULL,
  amount_curr_cd VARCHAR(50) NULL,
  Net_reporting_amount FLOAT NULL,
  Net_reporting_amount_debit FLOAT NULL,
  Net_reporting_amount_credit FLOAT NULL,
  reporting_amount_curr_cd VARCHAR(50) NULL,
  Net_functional_amount FLOAT NULL,
  Net_functional_debit_amount FLOAT NULL,
  Net_functional_credit_amount FLOAT NULL,
  functional_amount_curr_cd VARCHAR(50) NULL,
  count_je_id INT NULL
) stored AS orc;
