CREATE TABLE [GL_005_Agg_GL_Account](
	[coa_id] [int] NOT NULL,
	[account_type] [nvarchar](100) NULL,
	[account_sub_type] [nvarchar](100) NULL,
	[account_class] [nvarchar](100) NULL,
	[account_sub_class] [nvarchar](100) NULL,
	[gl_account_cd] [nvarchar](100) NOT NULL,
	[gl_account_name] [nvarchar](100) NULL,
	[ey_gl_account_name] [nvarchar](200) NULL,
	[period_id] [int] NOT NULL,
	[year_flag] [nvarchar](4) NULL,
	[period_flag] [nvarchar](4) NULL,
	[ey_period] [nvarchar](50) NULL,
	[year_flag_desc] [nvarchar](200) NULL,
	[period_flag_desc] [nvarchar](200) NULL,
	[bu_id] [int] NOT NULL,
	[source_id] [int] NOT NULL,
	[segment1_id] [int] NULL,
	[segment2_id] [int] NULL,
	/* Removed below columns since its has to pull dyanmically from cdm views by prabakar on july 1st  -- begin */
	--[bu_ref] [nvarchar](250) NULL,
	--[bu_group] [nvarchar](250) NULL,
	--[source_ref] [nvarchar](200) NULL,
	--[source_group] [nvarchar](250) NULL,
	--[segment1_ref] [nvarchar](250) NULL,
	--[segment1_group] [nvarchar](250) NULL,
	--[segment2_ref] [nvarchar](250) NULL,
	--[segment2_group] [nvarchar](250) NULL,
	/* Removed below columns since its has to pull dyanmically from cdm views by prabakar on july 1st  -- end */

	[user_listing_id] [int] NOT NULL,
	[preparer_ref] [nvarchar](200) NULL,
	[Preparer_department] [nvarchar](100) NULL,
	[approved_by_id] [int] NULL,
	[Approver_Ref] [nvarchar](104) NULL,
	[Approver_department] [nvarchar](100) NULL,
	[dr_cr_ind] [char](1) NULL,
	[reversal_ind] [char](1) NULL,
	[Sys_man_ind] [char](1) NULL,
	[entry_date_id] [int] NULL,
	[effective_date_id] [int] NULL,
	[amount_curr_cd] [nvarchar](50) NULL,
	[reporting_amount_curr_cd] [nvarchar](50) NULL,
	[functional_curr_cd] [nvarchar](50) NULL,
	[Net_amount] [float] NULL,
	[Net_amount_credit] [float] NULL,
	[Net_amount_debit] [float] NULL,
	[Net_reporting_amount] [float] NULL,
	[Net_reporting_amount_debit] [float] NULL,
	[Net_reporting_amount_credit] [float] NULL,
	[functional_amount] [float] NULL,
	[functional_debit_amount] [float] NULL,
	[functional_credit_amount] [float] NULL,
	[journal_type] [nvarchar](25) NULL
) ON [PRIMARY]