CREATE TABLE GL_012_Date_Validation (
  coa_id INT NULL,
  bu_id INT NULL,
  segment1_id INT NULL,
  segment2_id INT NULL,
  source_id INT NULL,
  user_listing_id INT NULL,
  approver_by_id INT NULL,
  year_flag nvarchar (25) NULL,
  period_flag nvarchar (25) NULL,
  ey_period nvarchar (100) NULL,
  entry_date DATETIME NULL,
  Effective_date DATETIME NULL,
  min_max_ent_eff_date DATETIME NULL,
  category nvarchar (100) NULL,
  je_id_count INT NULL,
  days_lag INT NULL,
  sys_manual_ind CHAR(1) NULL,
  journal_type nvarchar (25) NULL,
  functional_curr_cd nvarchar (100) NULL,
  reporting_amount_curr_cd nvarchar (100) NULL,
  net_reporting_amount FLOAT NULL,
  net_reporting_amount_credit FLOAT NULL,
  net_reporting_amount_debit FLOAT NULL,
  net_functional_amount FLOAT NULL,
  net_functional_credit_amount FLOAT NULL,
  net_functional_debit_amount FLOAT NULL,
  net_amount FLOAT NULL,
  net_amount_credit FLOAT NULL,
  net_amount_debit FLOAT NULL
)
