CREATE TABLE GL_017_Change_in_Preparers (
  bu_id INT,
  source_id INT,
  segment1_id INT,
  segment2_id INT,
  year_flag_desc VARCHAR(100),
  period_flag_desc VARCHAR(100),
  year_flag VARCHAR(25),
  period_flag VARCHAR(25),
  bu_group VARCHAR(200),
  bu_ref VARCHAR(200),
  segment1_ref VARCHAR(125),
  segment2_ref VARCHAR(125),
  segment1_group VARCHAR(100),
  segment2_group VARCHAR(100),
  Ey_period VARCHAR(50),
  source_group VARCHAR(200),
  Source_ref VARCHAR(200),
  sys_manual_ind VARCHAR(2),
  Journal_type VARCHAR(25),
  preparer_ref VARCHAR(200),
  department VARCHAR(100),
  Category VARCHAR(25),
  reporting_amount_curr_cd VARCHAR(25),
  functional_curr_cd VARCHAR(25)
) stored AS orc;
