CREATE TABLE GL_018_KPIs_unpivot (
  source_id INT,
  source_ref string,
  source_group string,
  Source_Cd string,
  Source_Desc string,
--bu_id int,
  bu_ref string,
  bu_group string,
  Preparer_Name string,
  preparer_ref string,
  Preparer_department string,
  journal_type string,
  segment1_ref string,
  segment1_group string,
  segment2_ref string,
  segment2_group string,
  year_flag_desc string,
  period_flag_desc string,
  ey_period string,
  Ratio_type string,
  Ratio string,
  Amount FLOAT,
  Multiplier INT
) stored AS orc;
