CREATE TABLE if not exists GL_017_Change_in_Preparers (
  bu_id INT NULL,
  source_id INT NULL,
  segment1_idINT NULL,
  segment2_idINT NULL,
  year_flag_desc varchar (100) NULL,
  period_flag_desc varchar (100) NULL,
  year_flag varchar (25) NULL,
  period_flag varchar (25) NULL,
  bu_group varchar (200) NULL,
  bu_ref varchar (200) NULL,
  segment1_ref varchar (125) NULL,
  segment2_ref varchar (125) NULL,
  segment1_group varchar (100) NULL,
  segment2_group varchar (100) NULL,
  Ey_period varchar (50) NULL,
  source_group varchar (200) NULL,
  Source_ref varchar (200) NULL,
  sys_manual_ind varchar (2) NULL,
  Journal_type varchar (25) NULL,
  preparer_ref varchar (200) NULL,
  department varchar (100) NULL,
  Category VARCHAR(25) NULL,
  reporting_amount_curr_cd varchar (25) NULL,
  functional_curr_cd varchar (25) NULL
)
