CREATE TABLE [GL_016_Data_stats_blanks](
	[Metric_B] [nvarchar](250) NULL,
	[Metric_Count_B] [int] NULL,
	[Period_Type_B] [nvarchar](250) NULL,
	[Period_Flag] [nvarchar](50) NULL,
	[Column_Name] [nvarchar](250) NULL,
	[Start_Date] [nvarchar](250) NULL,
	[End_Date] [nvarchar](250) NULL
) ON [PRIMARY]