CREATE TABLE GL_005_Agg_GL_Account (
  coa_id INT NOT NULL,
  account_type VARCHAR(100) NULL,
  account_sub_type VARCHAR(100) NULL,
  account_class VARCHAR(100) NULL,
  account_sub_class VARCHAR(100) NULL,
  gl_account_cd VARCHAR(100) NOT NULL,
  gl_account_name VARCHAR(100) NULL,
  ey_gl_account_name VARCHAR(200) NULL,
  period_id INT NOT NULL,
  year_flag VARCHAR(4) NULL,
  period_flag VARCHAR(4) NULL,
  ey_period VARCHAR(50) NULL,
  year_flag_desc VARCHAR(200) NULL,
  period_flag_desc VARCHAR(200) NULL,
  bu_id INT NOT NULL,
  source_id INT NOT NULL,
  segment1_id INT NULL,
  user_listing_id INT NOT NULL,
  preparer_ref VARCHAR(200) NULL,
  Preparer_department VARCHAR(100) NULL,
  approved_by_id INT NULL,
  Approver_Ref VARCHAR(104) NULL,
  Approver_department VARCHAR(100) NULL,
  dr_cr_ind CHAR(1) NULL,
  reversal_ind CHAR(1) NULL,
  Sys_man_ind CHAR(1) NULL,
  entry_date_id INT NULL,
  effective_date_id INT NULL,
  amount_curr_cd VARCHAR(50) NULL,
  reporting_amount_curr_cd VARCHAR(50) NULL,
  functional_curr_cd VARCHAR(50) NULL,
  Net_amount FLOAT NULL,
  Net_amount_credit FLOAT NULL,
  Net_amount_debit FLOAT NULL,
  Net_reporting_amount FLOAT NULL,
  Net_reporting_amount_debit FLOAT NULL,
  Net_reporting_amount_credit FLOAT NULL,
  functional_amount FLOAT NULL,
  functional_debit_amount FLOAT NULL,
  functional_credit_amount FLOAT NULL,
  journal_type VARCHAR(25) NULL
) stored AS orc;
