CREATE TABLE GL_012_Date_Analysis (
  Je_Id nvarchar (100) NULL,
  Je_Line_Id nvarchar (100) NULL,
  Account_Code nvarchar (200) NULL,
  GL_Account nvarchar (200) NULL,
  Account_Class nvarchar (200) NULL,
  Fiscal_period nvarchar (100) NULL,
  Year_flag nvarchar (25) NULL,
  Period_flag nvarchar (25) NULL,
  Bu_id INT NULL,
  Segment1_id INT NULL,
  Segment2_id INT NULL,
  Source_id INT NULL,
  User_listing_id INT NULL,
  Approver_by_id INT NULL,
  Journal_type nvarchar (25) NULL,
  Adjusted_fiscal_period nvarchar (50) NULL,
  Day_number_of_week INT NULL,
  Day_Of_Week nvarchar (50) NULL,
  Day_of_month INT NULL,
  Calendar_date DATETIME NULL,
  Sequence_number INT NULL,
  Reporting_currency_code nvarchar (50) NULL,
  Functional_Currency_Code nvarchar (50) NULL,
  Net_reporting_amount FLOAT NULL,
  Net_reporting_amount_credit FLOAT NULL,
  Net_reporting_amount_debit FLOAT NULL,
  Net_functional_amount FLOAT NULL,
  Net_functional_amount_debit FLOAT NULL,
  Net_functional_amount_credit FLOAT NULL,
  Net_Amount FLOAT NULL,
  Net_Amount_Credit FLOAT NULL,
  Net_Amount_Debit FLOAT NULL
)
