CREATE TABLE GL_004_Cashflow_Analysis (
  coa_id INT,
  bu_id INT,
  source_id INT,
  segment1_id INT,
  segment2_id INT,
  user_listing_id INT,
  approved_by_id INT,
  year_flag VARCHAR(3),
  period_flag VARCHAR(3),
  ey_period VARCHAR(16),
  sys_man_ind VARCHAR(25),
  journal_type VARCHAR(25),
  functional_curr_cd VARCHAR(25),
  reporting_curr_cd VARCHAR(25),
  source_type VARCHAR(25),
  net_reporting_amount FLOAT,
  net_reporting_amount_credit FLOAT,
  net_reporting_amount_debit FLOAT,
  net_functional_amount FLOAT,
  net_functional_amount_credit FLOAT,
  net_functional_amount_debit FLOAT
) stored AS orc;
