CREATE TABLE
    [GL_012_Date_Validation]
    (
        [coa_id] [INT] NULL,
        /*  Added below column to work with dynamic views to bring the data of bu, segment, source
        by Prabakar -- Begin */
        [bu_id] [INT] NULL,
        [segment1_id] [INT] NULL,
        [segment2_id] [INT] NULL,
        [source_id] [INT] NULL,
        [user_listing_id] INT NULL,
        [approver_by_id] INT NULL,
        /*  Added below column to work with dynamic views to bring the data of bu, segment, source
        by Prabakar -- end */
        [year_flag] [nvarchar](25) NULL,
        [period_flag] [nvarchar](25) NULL,
        [ey_period] [nvarchar](100) NULL,
        [entry_date] [DATETIME] NULL,
        [Effective_date] [DATETIME] NULL,
        [min_max_ent_eff_date] [DATETIME] NULL,
        [category] [nvarchar](100) NULL,
        [je_id_count] [INT] NULL,
        [days_lag] [INT] NULL,
        [sys_manual_ind] [CHAR](1) NULL,
        [journal_type] [nvarchar](25) NULL,
        [functional_curr_cd] [nvarchar](100) NULL,
        [reporting_amount_curr_cd] [nvarchar](100) NULL,
        [net_reporting_amount] [FLOAT] NULL,
        [net_reporting_amount_credit] [FLOAT] NULL,
        [net_reporting_amount_debit] [FLOAT] NULL,
        [net_functional_amount] [FLOAT] NULL,
        [net_functional_credit_amount] [FLOAT] NULL,
        [net_functional_debit_amount] [FLOAT] NULL,
        [net_amount] [FLOAT] NULL,
        [net_amount_credit] [FLOAT] NULL,
        [net_amount_debit] [FLOAT] NULL
        --[year_flag_desc] [nvarchar](100) NULL,
        --[period_flag_desc] [nvarchar](100) NULL,
        --[source_ref] [nvarchar](100) NULL,
        --[source_group] [nvarchar](100) NULL,
        --[preparer_ref] [nvarchar](200) NULL,
        --[preparer_department] [nvarchar](100) NULL,
        --[gl_account_cd] [nvarchar](100) NULL,
        --[ey_gl_account_name] [nvarchar](200) NULL,
        --[account_type] [nvarchar](100) NULL,
        --[account_sub_type] [nvarchar](100) NULL,
        --[ey_account_class] [nvarchar](100) NULL,
        --[account_sub_class] [nvarchar](100) NULL,
        --[ey_account_group_I] [nvarchar](100) NULL,
        --[bu_ref] [nvarchar](200) NULL,
        --[bu_group] [nvarchar](200) NULL,
        --[segment1_group] [nvarchar](100) NULL,
        --[segment2_group] [nvarchar](100) NULL,
        --[segment1_ref] [nvarchar](100) NULL,
        --[segment2_ref] [nvarchar](100) NULL,
        --[approver_department] [nvarchar](100) NULL,
        --[approver_ref] [nvarchar](100) NULL,
        --[max_effective_entry_diff] [int] NULL,
    )
