CREATE TABLE if not exists GL_005_Agg_GL_Account (
  coa_id INT NOT NULL,
  account_type varchar (100) NULL,
  account_sub_type varchar (100) NULL,
  account_class varchar (100) NULL,
  account_sub_class varchar (100) NULL,
  gl_account_cd varchar (100) NOT NULL,
  gl_account_name varchar (100) NULL,
  ey_gl_account_name varchar (200) NULL,
  period_id INT NOT NULL,
  year_flag varchar (4) NULL,
  period_flag varchar (4) NULL,
  ey_period varchar (50) NULL,
  year_flag_desc varchar (200) NULL,
  period_flag_desc varchar (200) NULL,
  bu_id INT NOT NULL,
  source_id INT NOT NULL,
  segment1_id INT NULL,
  user_listing_id INT NOT NULL,
  preparer_ref varchar (200) NULL,
  Preparer_department varchar (100) NULL,
  approved_by_id INT NULL,
  Approver_Ref varchar (104) NULL,
  Approver_department varchar (100) NULL,
  dr_cr_ind CHAR(1) NULL,
  reversal_ind CHAR(1) NULL,
  Sys_man_ind CHAR(1) NULL,
  entry_date_id INT NULL,
  effective_date_id INT NULL,
  amount_curr_cd varchar (50) NULL,
  reporting_amount_curr_cd varchar (50) NULL,
  functional_curr_cd varchar (50) NULL,
  Net_amount FLOAT NULL,
  Net_amount_credit FLOAT NULL,
  Net_amount_debit FLOAT NULL,
  Net_reporting_amount FLOAT NULL,
  Net_reporting_amount_debit FLOAT NULL,
  Net_reporting_amount_credit FLOAT NULL,
  functional_amount FLOAT NULL,
  functional_debit_amount FLOAT NULL,
  functional_credit_amount FLOAT NULL,
  journal_type varchar (25) NULL
)
