CREATE TABLE GL_018_KPIs_unpivot (
  source_id INT,
  source_ref VARCHAR(200),
  source_group VARCHAR(250),
  Source_Cd VARCHAR(25),
  Source_Desc VARCHAR(100),
--bu_id int,
  bu_ref VARCHAR(125),
  bu_group VARCHAR(125),
  Preparer_Name VARCHAR(200),
  preparer_ref VARCHAR(100),
  Preparer_department VARCHAR(100),
  journal_type VARCHAR(25),
  segment1_ref VARCHAR(250),
  segment1_group VARCHAR(250),
  segment2_ref VARCHAR(250),
  segment2_group VARCHAR(250),
  year_flag_desc VARCHAR(200),
  period_flag_desc VARCHAR(200),
  ey_period VARCHAR(50),
  Ratio_type VARCHAR(50),
  Ratio VARCHAR(50),
  Amount FLOAT,
  Multiplier INT
) stored AS orc;
