CREATE TABLE Trial_balance (
  coa_id INT,
  engagement_id string,
  bu_id INT,
  period_id INT,
  trial_balance_start_date_id INT,
  trial_balance_end_date_id INT,
  beginning_balance FLOAT,
  ending_balance FLOAT,
  balance_curr_cd VARCHAR(25),
  local_beginning_balance FLOAT,
  local_ending_balance FLOAT,
  local_curr_cd VARCHAR(25),
  reporting_beginning_balance FLOAT,
  reporting_ending_balance FLOAT,
  reporting_curr_cd VARCHAR(25),
  segment01 INT,
  segment02 INT,
  segment03 INT,
  segment04 INT,
  segment05 INT,
  ver_start_date_id INT,
  ver_end_date_id INT,
  ver_desc VARCHAR(100)
) stored AS orc;