	SELECT
		Source_ID     AS     [Source ID]
		,Source_Cd     AS     [Source Cd]
		,Source_Desc     AS     [Source Desc]
		--,Source_Ref     AS     [Source Ref]
		,preparer_ref     AS     [Preparer]
		,Preparer_Name     AS     [Preparer Name]
		,Preparer_department     AS     [Preparer department]
		,Source_group     AS     [Source group]
		,Source_Ref     AS     [Source]
		--,bu_id     AS     [BU]
		,Journal_Type     AS     [Journal Type]
		,Segment1_Group     AS     [Segment 1 Group]
		,Segment2_Group     AS     [Segment 2 Group]
		,Segment1_ref     AS     [Segment 1]
		,Segment2_ref     AS     [Segment 2]
		,bu_ref     AS     [Business Unit]
		,bu_group     AS     [Business Unit Group]
		,Year_flag_desc     AS     [Accounting period]
		,period_flag_desc    AS     [Accounting sub period]
		,ey_period     AS     [Fiscal period]
		,Ratio_type     AS     [Ratio type]
		,Ratio     AS     [Ratio]
		,Amount     AS     [Amount]
		,Multiplier     AS     [Multiplier]

	FROM dbo.GL_018_KPIs_unpivot
